name: cpp-linter

on: [pull_request]

jobs:
  cpp-linter:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v6
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake ninja-build doxygen clang-tidy libglib2.0-dev

      - name: Configure, build and test
        run: cmake --workflow --preset default-develop

      - uses: cpp-linter/cpp-linter-action@v2
        id: linter
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          database: 'build/default-develop'
          style: 'file'
          tidy-checks: ''
          files-changed-only: "true"
          step-summary: true
          file-annotations: "true"
          version: 20

      - if: steps.linter.outputs.checks-failed > 0
        run: exit 1
