name: Auto-Create Develop Branch
run-name: Recreating develop branch

on:
  pull_request_target:
    types: [closed]
    branches: [main]

jobs:
  create-develop-branch:
    if: ${{ github.event.pull_request.merged == true && startsWith(github.base_ref, 'main') && startsWith(github.head_ref, 'develop') }}
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Up Git
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"

      - name: Delete existing 'develop' branch (if exists)
        run: |
          git fetch origin
          git push origin --delete develop || echo "Branch 'develop' does not exist on remote."

      - name: Create new 'develop' branch from main
        run: |
          git checkout main
          git checkout -b develop
          git push origin develop

